ignore:
    - ".php-cs-fixer.dist.php"
    - "rector.php"
    - "src/BytesCachedHttpClientBundle.php"
    - "src/DependencyInjection/BytesCachedHttpClientExtension.php"
    - "src/Resources/config/services.php"
    - "src/BytesCachedHttpClientBundle.php"