name: Tests By Symfony Version

on:
  pull_request:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches:
      - main
      - 0.*
      - 1.*

jobs:
  symfony72:
    uses: mrgoodbytes8667/workflows/.github/workflows/run-tests-by-version.yml@php8.2-8.3
    with:
      phpUnitVersion: 9.6
      symfony: 7.2